#!/bin/bash

arr=(level terminal radar code civic robot )
pldm=()
count=0

for x in ${!arr[@]}
do
	str=${arr[$x]}
	len=${#str}
	rev=''
	for ((i=$len-1;i>=0;i--))
	do
    	rev="$rev${str:$i:1}"
	done
	if [[ $str == $rev ]]
	then
		pldm[$count]=$str
		count=$((count+1))
	fi
done
echo "Palindrome words are :" 
echo ${pldm[@]}
