#!/bin/bash
num=$1 
len=${#num} 
rev=' ' 
for (( i = "$len-1" ; i>=0 ; i-- )) 
do 
rev="$rev${num:$i:1}" 
done 
if [ $rev == $num ]
then 
echo "pelindrome"
else 
echo "not pelindrome"
fi
echo "reverse = $rev"
